# JVM & Gradle Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Environment
minecraft_version=1.21.1
neo_version=21.1.247
jei_version=19.42.0.385

# Mod Properties
group=invmod
displayname=Invasion
authors=Lieu, Elsee, UnstoppableN, Doenerstyle, Sollace
description=So you think your base is tough, do you?
mod_version=0.9.0

# Publishing (optional)
modrinth_loader_type=neoforge
modrinth_project_id=
