# JVM & Gradle Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Environment
minecraft_version=26.2
neo_version=26.2.0.35-beta
jei_version=30.15.0.115

# Mod Properties
group=invmod
displayname=Invasion
authors=Lieu, Elsee, UnstoppableN, Doenerstyle, Sollace
description=So you think your base is tough, do you?
mod_version=0.9.5

# Publishing (optional)
modrinth_loader_type=neoforge
modrinth_project_id=
