# JVM & Gradle Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Fabric Properties
# ? prüfbar unter https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.155.2+26.2
jei_version=30.14.0.94
mutant_monsters_version=26.2.1

# Mod Properties
group=invmod
displayname=Invasion
authors=Lieu, Elsee, UnstoppableN, Doenerstyle, Sollace
description=So you think your base is tough, do you?
mod_version=1.4.0

# Publishing (optional)
modrinth_loader_type=fabric
modrinth_project_id=

# Dependencies
